### PR TITLE
suggestion

### PR DESCRIPTION
**Pull request by J-N-K**
Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by Trinitus01** [comment]
Hi, thanks for the suggestion.

Are you sure to change this?
Because as you can see in line 1297 and after this line i use the same code for announcement.
For announcement it is necessary to use the json as key because there are more than 1 parameter to compare.
I dont know if maybe in the future tts will also need more parameters to compare.

Br,

Tom

**Comment by J-N-K** [comment]
See my new commit. I don't like using the json as converting to json is quite expensive (compared to a objects.hash).

**Comment by Trinitus01** [comment]
Ok i understand. And seems i missed the mvn spotless stuff.

**Comment by Trinitus01** [comment]
Put all your suggestions manually to the code because i changed all the comments (michi and yours) and im sure if i merge there are a lot of conflicts. I will mark them as your suggestions. Before i will test all the changes. What left, is the "equal-Travis" stuff. I do not understand why this tests do not recognise there is a "null test" before the use of equals.

**Comment by J-N-K** [comment]
Take a look here. Please check if the changed logix sounds reasonable.

**Comment by Trinitus01** [comment]
As i can see you converted a lot of "old style" programming to "new style" and use steams instead of loops. It reduces a lot of code. For me it looks reasonable. Does this kind of "if"-check reduce the null warnings? (To use local variables instead of a global in the "if"-check^^)

**Comment by J-N-K** [comment]
At least all places I touched do no longer show null-warnings (if I checked correctly).

**Comment by Trinitus01** [comment]
Ok, by the fact the improvements only part of the Connection class, maybe i can use your code as a template to fix the other classes warnings, too. If this is necessary at the moment i don't know. I only removed the StringUtils from the AccountHandler class. All the other classes i did not touch and leave the StringUtils stuff as it is.

**Comment by J-N-K** [comment]
Yes, no need to remove the other occurrences.

**Comment by Trinitus01** [comment]
Do i have to put your code into my local project and push or isn't it necessary?

**Comment by J-N-K** [comment]
You should have green  „merge“ button. Select „squash and merge“ if available. Maybe you need to tick „use your administrator rights“. After that, the PR To the openhab repo should be automatically updated.

**Pull request merged**
